---
- name: Créer l'utilisateur node_exporter
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: yes
    create_home: no


- name: Télécharger Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'


- name: Extraire l'archive Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes


- name: Copier le binaire Node Exporter
  copy:
    src: /tmp/node_exporter-1.9.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: '0755'
    remote_src: yes


- name: Créer le service systemd Node Exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target


- name: Recharger systemd
  systemd:
    daemon_reload: yes


- name: Activer et démarrer Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
