---
- name: Installation base de données
  hosts: databases
  become: yes

  tasks:

    - name: Installer MariaDB
      apt:
        name: mariadb-server
        state: present


    - name: Démarrer MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
